Reworked jinja Template for Zabbix Proxy 5.0 LTS
saltstack-formulas/zabbix-formula pull request #165
Opened 2023-08-29 16:07 UTC by xenadmin

### PR progress checklist (to be filled in by reviewers)

- [X] Changes to documentation are appropriate (or tick if not required)
- [X] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [X] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

### Describe the changes you're proposing

Reworked jinja Template for Zabbix Proxy 5.0 LTS

### Pillar / config required to test the proposed changes

### Debug log showing how the proposed changes work

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2023-08-30 18:01 UTC, hatifnatt requested changes
Please update commit message according with formulas guidelines
https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#commit-message-formatting

2023-08-31 14:28 UTC, xenadmin commented
>Please update commit message according with formulas guidelines

I've read that, and I have no idea that I need to change, sorry. Can you please give me a hint what exactly is missing?

2023-08-31 14:29 UTC, xenadmin commented on zabbix/files/default/etc/zabbix/zabbix_proxy.conf.jinja
> +#		Whether remote commands from Zabbix server are allowed.
Technically not, but I did my best at _exactly_ comparing the original conf from `zabbix-proxy-sqlite3_5.0.37-1+debian11_amd64.deb` with the jinja and I adopted _every_ little change. 
Ps.: If this gets merged, I prepare the next PR with the changes for Zabbix proxy 6.0 LTS.

2023-08-31 17:17 UTC, hatifnatt commented on zabbix/files/default/etc/zabbix/zabbix_proxy.conf.jinja
> +#		Whether remote commands from Zabbix server are allowed.
Ok, lets update those spaces.

2023-08-31 17:20 UTC, hatifnatt approved these changes
Unfortunately CI is broken but changes looks good for me.

2023-08-31 17:23 UTC, merged